package proto_id

import (
	"xiao/proto/proto_game"
	"xiao/proto/proto_login"
	"xiao/proto/proto_player"

	"github.com/gogo/protobuf/proto"
)

func NewMessage(id int) proto.Message {
	switch id {
	case 1:
		return new(proto_login.Ping)
	case 2:
		return new(proto_login.Pong)
	case 3:
		return new(proto_login.LoginKey)
	case 4:
		return new(proto_login.LoginRequest)
	case 5:
		return new(proto_login.LoginResponse)
	case 6:
		return new(proto_player.GetPlayerData)
	case 7:
		return new(proto_login.Logout)
	case 14:
		return new(proto_player.S2CFuncOpen)
	case 15:
		return new(proto_player.C2SGetMailList)
	case 16:
		return new(proto_player.S2CGetMailList)
	case 17:
		return new(proto_player.C2SGetMailDetail)
	case 18:
		return new(proto_player.S2CGetMailDetail)
	case 19:
		return new(proto_player.S2CNewMail)
	case 20:
		return new(proto_player.C2SDeleteMail)
	case 21:
		return new(proto_player.S2CDeleteMail)
	case 22:
		return new(proto_player.C2SReceiveMailAward)
	case 23:
		return new(proto_player.S2CReceiveMailAward)
	case 25:
		return new(proto_player.S2CBag)
	case 26:
		return new(proto_player.S2CNotice)
	case 27:
		return new(proto_player.C2SGMCommand)
	case 28:
		return new(proto_player.C2SPlayerRename)
	case 29:
		return new(proto_player.S2CPlayerRename)
	case 30:
		return new(proto_player.C2SChangeHead)
	case 31:
		return new(proto_player.S2CChangeHead)
	case 32:
		return new(proto_player.C2SGetAllTask)
	case 33:
		return new(proto_player.S2CGetAllTask)
	case 34:
		return new(proto_player.C2SReceiveTaskAward)
	case 35:
		return new(proto_player.S2CReceiveTaskAward)
	case 36:
		return new(proto_player.S2CTaskUpdate)
	case 37:
		return new(proto_player.S2CResourceChanged)
	case 38:
		return new(proto_player.S2CGameInfoChanged)
	case 39:
		return new(proto_player.S2CAnnouncement)
	case 40:
		return new(proto_player.C2SGetFuncState)
	case 41:
		return new(proto_player.C2SGetRoomPlayerInfo)
	case 42:
		return new(proto_player.S2CGetRoomPlayerInfo)
	case 43:
		return new(proto_player.S2CKick)
	case 80:
		return new(proto_game.C2SRoomOptions)
	case 81:
		return new(proto_game.S2CRoomOptions)
	case 82:
		return new(proto_game.C2SGetNumOfPlayers)
	case 83:
		return new(proto_game.S2CGetNumOfPlayers)
	case 84:
		return new(proto_game.C2SEnter)
	case 85:
		return new(proto_game.S2CEnter)
	case 86:
		return new(proto_game.C2SLeave)
	case 87:
		return new(proto_game.S2CLeave)
	case 88:
		return new(proto_game.C2SCheckEnter)
	case 89:
		return new(proto_game.S2CAutoBuy)
	case 90:
		return new(proto_game.S2CGameKick)
	case 100:
		return new(proto_game.S2CTable)
	case 101:
		return new(proto_game.S2CPlayerEnter)
	case 102:
		return new(proto_game.S2CPlayerLeave)
	case 103:
		return new(proto_game.C2SOp)
	case 104:
		return new(proto_game.S2COp)
	case 105:
		return new(proto_game.S2CGameStart)
	case 106:
		return new(proto_game.S2CLoopOver)
	case 107:
		return new(proto_game.S2CRoundOver)
	case 108:
		return new(proto_game.S2CDealCards)
	case 109:
		return new(proto_game.S2CShowCards)
	case 110:
		return new(proto_game.S2CSettle)
	case 111:
		return new(proto_game.S2CGameOver)
	case 112:
		return new(proto_game.S2CWaitOps)
	case 113:
		return new(proto_game.C2SStandUp)
	case 114:
		return new(proto_game.S2CStandUp)
	case 115:
		return new(proto_game.C2SSitDown)
	case 116:
		return new(proto_game.S2CSitDown)
	case 117:
		return new(proto_game.S2CMoneyNotEnough)
	case 118:
		return new(proto_game.C2SBuy)
	case 119:
		return new(proto_game.S2CBuy)
	case 120:
		return new(proto_game.C2STips)
	case 121:
		return new(proto_game.S2CTips)
	case 122:
		return new(proto_game.S2CLoopOverBefore)

	}

	return nil
}

func MessageID(msg proto.Message) int {
	switch msg.(type) {
	case *proto_login.Ping:
		return 1
	case *proto_login.Pong:
		return 2
	case *proto_login.LoginKey:
		return 3
	case *proto_login.LoginRequest:
		return 4
	case *proto_login.LoginResponse:
		return 5
	case *proto_player.GetPlayerData:
		return 6
	case *proto_login.Logout:
		return 7
	case *proto_player.S2CFuncOpen:
		return 14
	case *proto_player.C2SGetMailList:
		return 15
	case *proto_player.S2CGetMailList:
		return 16
	case *proto_player.C2SGetMailDetail:
		return 17
	case *proto_player.S2CGetMailDetail:
		return 18
	case *proto_player.S2CNewMail:
		return 19
	case *proto_player.C2SDeleteMail:
		return 20
	case *proto_player.S2CDeleteMail:
		return 21
	case *proto_player.C2SReceiveMailAward:
		return 22
	case *proto_player.S2CReceiveMailAward:
		return 23
	case *proto_player.S2CBag:
		return 25
	case *proto_player.S2CNotice:
		return 26
	case *proto_player.C2SGMCommand:
		return 27
	case *proto_player.C2SPlayerRename:
		return 28
	case *proto_player.S2CPlayerRename:
		return 29
	case *proto_player.C2SChangeHead:
		return 30
	case *proto_player.S2CChangeHead:
		return 31
	case *proto_player.C2SGetAllTask:
		return 32
	case *proto_player.S2CGetAllTask:
		return 33
	case *proto_player.C2SReceiveTaskAward:
		return 34
	case *proto_player.S2CReceiveTaskAward:
		return 35
	case *proto_player.S2CTaskUpdate:
		return 36
	case *proto_player.S2CResourceChanged:
		return 37
	case *proto_player.S2CGameInfoChanged:
		return 38
	case *proto_player.S2CAnnouncement:
		return 39
	case *proto_player.C2SGetFuncState:
		return 40
	case *proto_player.C2SGetRoomPlayerInfo:
		return 41
	case *proto_player.S2CGetRoomPlayerInfo:
		return 42
	case *proto_player.S2CKick:
		return 43
	case *proto_game.C2SRoomOptions:
		return 80
	case *proto_game.S2CRoomOptions:
		return 81
	case *proto_game.C2SGetNumOfPlayers:
		return 82
	case *proto_game.S2CGetNumOfPlayers:
		return 83
	case *proto_game.C2SEnter:
		return 84
	case *proto_game.S2CEnter:
		return 85
	case *proto_game.C2SLeave:
		return 86
	case *proto_game.S2CLeave:
		return 87
	case *proto_game.C2SCheckEnter:
		return 88
	case *proto_game.S2CAutoBuy:
		return 89
	case *proto_game.S2CGameKick:
		return 90
	case *proto_game.S2CTable:
		return 100
	case *proto_game.S2CPlayerEnter:
		return 101
	case *proto_game.S2CPlayerLeave:
		return 102
	case *proto_game.C2SOp:
		return 103
	case *proto_game.S2COp:
		return 104
	case *proto_game.S2CGameStart:
		return 105
	case *proto_game.S2CLoopOver:
		return 106
	case *proto_game.S2CRoundOver:
		return 107
	case *proto_game.S2CDealCards:
		return 108
	case *proto_game.S2CShowCards:
		return 109
	case *proto_game.S2CSettle:
		return 110
	case *proto_game.S2CGameOver:
		return 111
	case *proto_game.S2CWaitOps:
		return 112
	case *proto_game.C2SStandUp:
		return 113
	case *proto_game.S2CStandUp:
		return 114
	case *proto_game.C2SSitDown:
		return 115
	case *proto_game.S2CSitDown:
		return 116
	case *proto_game.S2CMoneyNotEnough:
		return 117
	case *proto_game.C2SBuy:
		return 118
	case *proto_game.S2CBuy:
		return 119
	case *proto_game.C2STips:
		return 120
	case *proto_game.S2CTips:
		return 121
	case *proto_game.S2CLoopOverBefore:
		return 122

	}

	return 0
}
