--[[ This file is generated by tools, do not modify it manully! ]]

local LaunchView = { 
	self,           --[[GameObject]]
}
LaunchView.__name = "LaunchView"

function LaunchView.load(view, parent, path)
	parent, path = parent or 0, path or ""
	local self = clone(LaunchView)
	self.self = G.api.View.Lookup(view, parent, path, "Canvas")
	return self
end

return LaunchView
