--[[ This file is generated by tools, do not modify it manully! ]]

local LoadingView = { 
	self,           --[[GameObject]]
	pivot,          --[[GameObject]]
	pregress_bg,    --[[Image]]
	showtext,       --[[Text]]
	remind,         --[[Text]]
}
LoadingView.__name = "LoadingView"

function LoadingView.load(view, parent, path)
	parent, path = parent or 0, path or ""
	local self = clone(LoadingView)
	self.self = G.api.View.Lookup(view, parent, path, "Canvas")
	self.pivot = G.api.View.Lookup(view, self.self, "pivot", "GameObject")
	self.pregress_bg = G.api.View.Lookup(view, self.self, "pivot/down/pregress_bg", "Image")
	self.showtext = G.api.View.Lookup(view, self.self, "pivot/down/showtext", "Text")
	self.remind = G.api.View.Lookup(view, self.self, "pivot/down/remind", "Text")
	return self
end

return LoadingView
